# Generated by Django 2.2.8 on 2021-05-01 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='trigger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Trigger'),
            preserve_default=False,
        ),
    ]
