# Generated by Django 2.2.8 on 2021-05-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='regno',
        ),
        migrations.RemoveField(
            model_name='student',
            name='trigger',
        ),
    ]
